Imports MySql.Data.MySqlClient
Imports System.IO
Imports System.Drawing.Imaging
Imports System.Text.RegularExpressions
Imports Tesseract

Public Class Barangay_Residences

    Private profileImageBytes As Byte() = Nothing
    Private idFrontImageBytes As Byte() = Nothing
    Private idBackImageBytes As Byte() = Nothing

    Private Sub Barangay_Residences_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Me.TopMost = True
        Me.KeyPreview = True
        frmMain.Enabled = False

        cboSuffix.Items.AddRange({"N/A", "JR.", "SR.", "II", "III", "IV", "V"})
        cboSuffix.SelectedIndex = 0

        cboCivilStatus.Items.AddRange({"SINGLE", "MARRIED", "WIDOWED", "SEPARATED", "DIVORCED"})
        cboCivilStatus.SelectedIndex = 0

        cboGender.Items.AddRange({"MALE", "FEMALE", "OTHER"})
        cboGender.SelectedIndex = 0

        txtBarangay.Text = "PUTATAN"
        txtBarangay.ReadOnly = True

        txtCity.Text = "MUNTINLUPA CITY"
        txtCity.ReadOnly = True

        txtUsername.Tag = "AutoGenerated"
        GenerateResidentCode()
        ClearAllValidationLabels()
    End Sub

    Private Sub Barangay_Residences_KeyDown(sender As Object, e As KeyEventArgs) Handles MyBase.KeyDown
        If e.KeyCode = Keys.Enter Then
            e.SuppressKeyPress = True
            btnSubmit.PerformClick()
        End If
    End Sub

    Private Sub ConvertToUpperCase_KeyPress(sender As Object, e As KeyPressEventArgs) Handles _
        txtLastname.KeyPress, txtFirstname.KeyPress, txtMiddlename.KeyPress,
        txtStreetAddress.KeyPress, txtBirthPlace.KeyPress

        If Char.IsLower(e.KeyChar) Then
            e.KeyChar = Char.ToUpper(e.KeyChar)
        End If
    End Sub

    Private Sub ClearAllValidationLabels()
        SetFeedbackLabel(lblLastnameError, "", False)
        SetFeedbackLabel(lblFirstnameError, "", False)
        SetFeedbackLabel(lblMiddlenameError, "", False)
        SetFeedbackLabel(lblStreetAddressError, "", False)
        SetFeedbackLabel(lblBirthPlaceError, "", False)
        SetFeedbackLabel(lblMobileError, "", False)
        SetFeedbackLabel(lblEmailError, "", False)
        SetFeedbackLabel(lblUsernameError, "", False)
        SetFeedbackLabel(lblConfirmPassError, "", False)
        SetFeedbackLabel(lblPictureError, "", False)
        SetFeedbackLabel(lblIdError, "", False)
    End Sub

    Private Sub SetFeedbackLabel(lbl As Label, message As String, isError As Boolean)
        If lbl Is Nothing Then Exit Sub
        lbl.Text = message
        If String.IsNullOrEmpty(message) Then
            lbl.ForeColor = Color.Black
        ElseIf isError Then
            lbl.ForeColor = Color.Red
        Else
            lbl.ForeColor = Color.Green
        End If
    End Sub

    Private Function GetNextResidentCode() As String
        Dim nextCode As String = "RES-001"
        Try
            connection()
            sql = "SELECT ResidentCode FROM residences WHERE ResidentCode LIKE 'RES-%' ORDER BY ResidentID DESC LIMIT 1"
            cmd = New MySqlCommand(sql, cn)
            dr = cmd.ExecuteReader()

            If dr.Read() Then
                Dim lastCode As String = dr("ResidentCode").ToString()
                If lastCode.Contains("-") Then
                    Dim parts() As String = lastCode.Split("-"c)
                    Dim numericPart As Integer
                    If Integer.TryParse(parts(1), numericPart) Then
                        nextCode = "RES-" & (numericPart + 1).ToString("D3")
                    End If
                End If
            End If
            dr.Close()
        Catch ex As Exception
        Finally
            CloseConnection()
        End Try
        Return nextCode
    End Function

    Private Sub GenerateResidentCode()
        Dim code As String = GetNextResidentCode()
        If lblStaffCode IsNot Nothing Then
            lblStaffCode.Text = code
        End If
    End Sub

    Private Sub UpdateUsernameSuggestion() Handles txtFirstname.TextChanged
        If txtUsername.Tag Is Nothing OrElse txtUsername.Tag.ToString() <> "AutoGenerated" Then Exit Sub

        If String.IsNullOrWhiteSpace(txtFirstname.Text) Then
            txtUsername.Clear()
            Exit Sub
        End If

        Dim cleanFirst As String = txtFirstname.Text.Trim().Replace(" ", "").Replace(".", "").ToLower()
        Dim suggestedUser As String = $"{cleanFirst}res"

        Try
            connection()
            Dim counter As Integer = 1
            Dim checkUser As String = suggestedUser

            Do
                sql = "SELECT Email FROM residences WHERE LOWER(Email)=LOWER(@uname)"
                cmd = New MySqlCommand(sql, cn)
                cmd.Parameters.AddWithValue("@uname", checkUser)
                dr = cmd.ExecuteReader()

                If Not dr.HasRows Then
                    dr.Close()
                    Exit Do
                End If
                dr.Close()

                checkUser = $"{suggestedUser}{counter}"
                counter += 1
            Loop

            txtUsername.Text = checkUser
            txtUsername.SelectionStart = txtUsername.TextLength
        Catch ex As Exception
            txtUsername.Text = suggestedUser
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub txtUsername_KeyPress(sender As Object, e As KeyPressEventArgs) Handles txtUsername.KeyPress
        txtUsername.Tag = "ManualEdited"
    End Sub

    Private Sub txtMobileNumber_KeyPress(sender As Object, e As KeyPressEventArgs) Handles txtMobileNumber.KeyPress
        If Not Char.IsControl(e.KeyChar) AndAlso Not Char.IsDigit(e.KeyChar) Then
            e.Handled = True
        End If
    End Sub

    Private Sub txtLastname_TextChanged(sender As Object, e As EventArgs) Handles txtLastname.TextChanged
        If String.IsNullOrWhiteSpace(txtLastname.Text) Then
            SetFeedbackLabel(lblLastnameError, "Lastname is required.", True)
        ElseIf Not Regex.IsMatch(txtLastname.Text.Trim(), "^[a-zA-ZñÑ\s]+$") Then
            SetFeedbackLabel(lblLastnameError, "Letters only (no numbers/symbols).", True)
        Else
            SetFeedbackLabel(lblLastnameError, "✓ OK", False)
        End If
    End Sub

    Private Sub txtFirstname_TextChanged(sender As Object, e As EventArgs) Handles txtFirstname.TextChanged
        If String.IsNullOrWhiteSpace(txtFirstname.Text) Then
            SetFeedbackLabel(lblFirstnameError, "Firstname is required.", True)
        ElseIf Not Regex.IsMatch(txtFirstname.Text.Trim(), "^[a-zA-ZñÑ\s]+$") Then
            SetFeedbackLabel(lblFirstnameError, "Letters only (no numbers/symbols).", True)
        Else
            SetFeedbackLabel(lblFirstnameError, "✓ OK", False)
        End If
    End Sub

    Private Sub txtMiddlename_TextChanged(sender As Object, e As EventArgs) Handles txtMiddlename.TextChanged
        If Not String.IsNullOrWhiteSpace(txtMiddlename.Text) AndAlso Not Regex.IsMatch(txtMiddlename.Text.Trim(), "^[a-zA-ZñÑ\s]+$") Then
            SetFeedbackLabel(lblMiddlenameError, "Letters only.", True)
        Else
            SetFeedbackLabel(lblMiddlenameError, "✓ OK", False)
        End If
    End Sub

    Private Sub txtStreetAddress_TextChanged(sender As Object, e As EventArgs) Handles txtStreetAddress.TextChanged
        If String.IsNullOrWhiteSpace(txtStreetAddress.Text) Then
            SetFeedbackLabel(lblStreetAddressError, "Street address is required.", True)
        Else
            SetFeedbackLabel(lblStreetAddressError, "✓ OK", False)
        End If
    End Sub

    Private Sub txtBirthPlace_TextChanged(sender As Object, e As EventArgs) Handles txtBirthPlace.TextChanged
        If String.IsNullOrWhiteSpace(txtBirthPlace.Text) Then
            SetFeedbackLabel(lblBirthPlaceError, "Birth place is required.", True)
        Else
            SetFeedbackLabel(lblBirthPlaceError, "✓ OK", False)
        End If
    End Sub

    Private Sub txtMobileNumber_TextChanged(sender As Object, e As EventArgs) Handles txtMobileNumber.TextChanged
        Dim val As String = txtMobileNumber.Text.Trim()

        If String.IsNullOrWhiteSpace(val) Then
            SetFeedbackLabel(lblMobileError, "Mobile number is required.", True)
            Exit Sub
        End If

        If Not val.StartsWith("09") Then
            SetFeedbackLabel(lblMobileError, "Must start with 09.", True)
            Exit Sub
        End If

        If val.Length <> 11 Then
            SetFeedbackLabel(lblMobileError, "Must be exactly 11 digits.", True)
            Exit Sub
        End If

        Try
            connection()
            Dim count As Integer = 0
            sql = "SELECT COUNT(*) FROM residences WHERE MobileNumber = @mobile"
            Using localCmd As New MySqlCommand(sql, cn)
                localCmd.Parameters.AddWithValue("@mobile", val)
                count = Convert.ToInt32(localCmd.ExecuteScalar())
            End Using

            If count > 0 Then
                SetFeedbackLabel(lblMobileError, "Mobile number already registered!", True)
            Else
                SetFeedbackLabel(lblMobileError, "✓ OK", False)
            End If
        Catch ex As Exception
            SetFeedbackLabel(lblMobileError, "Error verifying mobile number.", True)
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub txtEmail_TextChanged(sender As Object, e As EventArgs) Handles txtEmail.TextChanged
        Dim val As String = txtEmail.Text.Trim().ToLower()

        If String.IsNullOrWhiteSpace(val) Then
            SetFeedbackLabel(lblEmailError, "Email is required.", True)
            Exit Sub
        End If

        Dim strictGmailRegex As New Regex("^[a-zA-Z0-9._%+-]+@gmail\.com$", RegexOptions.IgnoreCase)
        If Not strictGmailRegex.IsMatch(val) Then
            SetFeedbackLabel(lblEmailError, "Must end strictly with @gmail.com.", True)
            Exit Sub
        End If

        Try
            connection()
            Dim count As Integer = 0
            sql = "SELECT COUNT(*) FROM residences WHERE LOWER(Email) = LOWER(@email)"
            Using localCmd As New MySqlCommand(sql, cn)
                localCmd.Parameters.AddWithValue("@email", val)
                count = Convert.ToInt32(localCmd.ExecuteScalar())
            End Using

            If count > 0 Then
                SetFeedbackLabel(lblEmailError, "Email address already registered!", True)
            Else
                SetFeedbackLabel(lblEmailError, "✓ OK", False)
            End If
        Catch ex As Exception
            SetFeedbackLabel(lblEmailError, "Error verifying email address.", True)
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub txtUsername_TextChanged(sender As Object, e As EventArgs) Handles txtUsername.TextChanged
        Dim val As String = txtUsername.Text.Trim()

        If String.IsNullOrWhiteSpace(val) Then
            SetFeedbackLabel(lblUsernameError, "Username is required.", True)
            Exit Sub
        End If

        If val.ToLower().Contains("admin") Then
            SetFeedbackLabel(lblUsernameError, "Usernames related to 'admin' are prohibited.", True)
            Exit Sub
        End If

        Try
            connection()
            Dim count As Integer = 0
            sql = "SELECT COUNT(*) FROM residences WHERE LOWER(Email) = LOWER(@uname)"
            Using localCmd As New MySqlCommand(sql, cn)
                localCmd.Parameters.AddWithValue("@uname", val)
                count = Convert.ToInt32(localCmd.ExecuteScalar())
            End Using

            If count > 0 Then
                SetFeedbackLabel(lblUsernameError, "Username already taken!", True)
            Else
                SetFeedbackLabel(lblUsernameError, "✓ OK", False)
            End If
        Catch ex As Exception
            SetFeedbackLabel(lblUsernameError, "Error verifying username.", True)
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub txtPassword_TextChanged(sender As Object, e As EventArgs) Handles txtPassword.TextChanged, txtConfirmPass.TextChanged
        Dim hasUpper As Boolean = txtPassword.Text.Any(AddressOf Char.IsUpper)
        Dim hasLower As Boolean = txtPassword.Text.Any(AddressOf Char.IsLower)

        If String.IsNullOrWhiteSpace(txtPassword.Text) Then
            SetFeedbackLabel(lblConfirmPassError, "Password is required.", True)
        ElseIf Not hasUpper OrElse Not hasLower OrElse txtPassword.Text.Length < 6 Then
            SetFeedbackLabel(lblConfirmPassError, "Min 6 chars, uppercase & lowercase.", True)
        ElseIf txtPassword.Text <> txtConfirmPass.Text Then
            SetFeedbackLabel(lblConfirmPassError, "Passwords do not match.", True)
        Else
            SetFeedbackLabel(lblConfirmPassError, "✓ Passwords Match", False)
        End If
    End Sub

    Private Sub picUser_DoubleClick(sender As Object, e As EventArgs) Handles picUser.DoubleClick
        Using ofd As New OpenFileDialog()
            ofd.Filter = "Image Files (*.jpg;*.jpeg;*.png)|*.jpg;*.jpeg;*.png"
            If ofd.ShowDialog() = DialogResult.OK Then
                picUser.SizeMode = PictureBoxSizeMode.StretchImage
                picUser.Image = Image.FromFile(ofd.FileName)

                Using ms As New MemoryStream()
                    picUser.Image.Save(ms, System.Drawing.Imaging.ImageFormat.Jpeg)
                    profileImageBytes = ms.ToArray()
                End Using
                SetFeedbackLabel(lblPictureError, "✓ Uploaded", False)
            End If
        End Using
    End Sub

    Private Sub picIDFront_DoubleClick(sender As Object, e As EventArgs) Handles picIDFront.DoubleClick
        Using ofd As New OpenFileDialog()
            ofd.Filter = "Image Files (*.jpg;*.jpeg;*.png)|*.jpg;*.jpeg;*.png"
            If ofd.ShowDialog() = DialogResult.OK Then
                picIDFront.SizeMode = PictureBoxSizeMode.StretchImage

                If picIDFront.Image IsNot Nothing Then picIDFront.Image.Dispose()
                picIDFront.Image = Image.FromFile(ofd.FileName)

                Using ms As New MemoryStream()
                    picIDFront.Image.Save(ms, System.Drawing.Imaging.ImageFormat.Jpeg)
                    idFrontImageBytes = ms.ToArray()
                End Using
                SetFeedbackLabel(lblIdError, "✓ Front Uploaded", False)

                ExtractAndParseIDText(ofd.FileName)
            End If
        End Using
    End Sub

    Private Sub picIDBack_DoubleClick(sender As Object, e As EventArgs) Handles picIDBack.DoubleClick
        Using ofd As New OpenFileDialog()
            ofd.Filter = "Image Files (*.jpg;*.jpeg;*.png)|*.jpg;*.jpeg;*.png"
            If ofd.ShowDialog() = DialogResult.OK Then
                picIDBack.SizeMode = PictureBoxSizeMode.StretchImage

                If picIDBack.Image IsNot Nothing Then picIDBack.Image.Dispose()
                picIDBack.Image = Image.FromFile(ofd.FileName)

                Using ms As New MemoryStream()
                    picIDBack.Image.Save(ms, System.Drawing.Imaging.ImageFormat.Jpeg)
                    idBackImageBytes = ms.ToArray()
                End Using
                SetFeedbackLabel(lblIdError, "✓ Front & Back Uploaded", False)
            End If
        End Using
    End Sub

    Private Sub ExtractAndParseIDText(imagePath As String)
        Dim tessPath As String = Path.Combine(Application.StartupPath, "tessdata")

        If Not Directory.Exists(tessPath) OrElse Not File.Exists(Path.Combine(tessPath, "eng.traineddata")) Then
            MsgBox("Missing tessdata folder or eng.traineddata file!", MsgBoxStyle.Exclamation, "OCR Initialization Error")
            Exit Sub
        End If

        Try
            Using rawImg As New Bitmap(imagePath)
                Using processedImg As Bitmap = PreprocessImageForOCR(rawImg)
                    Using ms As New MemoryStream()
                        processedImg.Save(ms, System.Drawing.Imaging.ImageFormat.Png)
                        ms.Position = 0

                        Using engine As New TesseractEngine(tessPath, "eng", EngineMode.Default)
                            engine.SetVariable("tessedit_char_whitelist", "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789/-,. ")
                            Using img As Pix = Pix.LoadFromMemory(ms.ToArray())
                                Using page As Page = engine.Process(img)
                                    Dim text As String = page.GetText()
                                    AutoFillFromOCR(text)
                                End Using
                            End Using
                        End Using
                    End Using
                End Using
            End Using
        Catch ex As Exception
        End Try
    End Sub

    Private Function PreprocessImageForOCR(original As Bitmap) As Bitmap
        Dim newBitmap As New Bitmap(original.Width, original.Height)
        Using g As Graphics = Graphics.FromImage(newBitmap)
            Dim colorMatrix As New ColorMatrix(New Single()() {
                New Single() {0.3F, 0.3F, 0.3F, 0, 0},
                New Single() {0.59F, 0.59F, 0.59F, 0, 0},
                New Single() {0.11F, 0.11F, 0.11F, 0, 0},
                New Single() {0, 0, 0, 1, 0},
                New Single() {0, 0, 0, 0, 1}
            })

            Using attributes As New ImageAttributes()
                attributes.SetColorMatrix(colorMatrix)
                g.DrawImage(original, New Rectangle(0, 0, original.Width, original.Height),
                            0, 0, original.Width, original.Height, GraphicsUnit.Pixel, attributes)
            End Using
        End Using
        Return newBitmap
    End Function

    Private Sub AutoFillFromOCR(scannedText As String)
        If String.IsNullOrWhiteSpace(scannedText) Then Exit Sub

        Dim lines() As String = scannedText.Split(New String() {vbCrLf, vbLf}, StringSplitOptions.RemoveEmptyEntries)
        Dim cleanedLines As New List(Of String)()

        For Each l As String In lines
            Dim trimmed As String = l.Trim()
            If trimmed.Length >= 2 Then cleanedLines.Add(trimmed)
        Next

        For i As Integer = 0 To cleanedLines.Count - 1
            Dim line As String = cleanedLines(i)

            If Regex.IsMatch(line, "(Last Name|Surname|Apelyido)", RegexOptions.IgnoreCase) Then
                For j As Integer = i + 1 To Math.Min(i + 2, cleanedLines.Count - 1)
                    Dim val As String = CleanNameString(cleanedLines(j)).ToUpper()
                    If val.Length > 2 AndAlso Not IsHeaderKeyword(val) Then
                        txtLastname.Text = val
                        Exit For
                    End If
                Next
            End If

            If Regex.IsMatch(line, "(First Name|Given Name|Mga Pangalan|Pangalan)", RegexOptions.IgnoreCase) Then
                For j As Integer = i + 1 To Math.Min(i + 2, cleanedLines.Count - 1)
                    Dim val As String = CleanNameString(cleanedLines(j)).ToUpper()
                    If val.Length > 2 AndAlso Not IsHeaderKeyword(val) Then
                        txtFirstname.Text = val
                        Exit For
                    End If
                Next
            End If

            If Regex.IsMatch(line, "(Middle Name|Gitnang Apelyido)", RegexOptions.IgnoreCase) Then
                For j As Integer = i + 1 To Math.Min(i + 2, cleanedLines.Count - 1)
                    Dim val As String = CleanNameString(cleanedLines(j)).ToUpper()
                    If val.Length > 2 AndAlso Not IsHeaderKeyword(val) Then
                        txtMiddlename.Text = val
                        Exit For
                    End If
                Next
            End If

            If Regex.IsMatch(line, "(Address|Tirahan)", RegexOptions.IgnoreCase) Then
                For j As Integer = i + 1 To Math.Min(i + 2, cleanedLines.Count - 1)
                    Dim val As String = cleanedLines(j).Trim().ToUpper()
                    If val.Length > 3 AndAlso Not IsHeaderKeyword(val) Then
                        txtStreetAddress.Text = val
                        Exit For
                    End If
                Next
            End If

            If Regex.IsMatch(line, "(Place of Birth|Kapanakan|Lugar)", RegexOptions.IgnoreCase) Then
                For j As Integer = i + 1 To Math.Min(i + 2, cleanedLines.Count - 1)
                    Dim val As String = CleanNameString(cleanedLines(j)).ToUpper()
                    If val.Length > 2 AndAlso Not IsHeaderKeyword(val) Then
                        txtBirthPlace.Text = val
                        Exit For
                    End If
                Next
            End If

            Dim dateMatch As Match = Regex.Match(line, "\b(\d{1,2}[/-]\d{1,2}[/-]\d{2,4}|\d{4}[/-]\d{1,2}[/-]\d{1,2}|(JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC)[A-Z]*\s+\d{1,2},?\s+\d{4})\b", RegexOptions.IgnoreCase)
            If dateMatch.Success Then
                Dim parsedDate As DateTime
                If DateTime.TryParse(dateMatch.Value, parsedDate) Then
                    dtpBirthday.Value = parsedDate
                End If
            End If

            If Regex.IsMatch(line, "\b(MALE|FEMALE|Kasarian)\b", RegexOptions.IgnoreCase) Then
                If line.ToUpper().Contains("FEMALE") OrElse line.ToUpper().Contains("BABAE") Then
                    cboGender.Text = "FEMALE"
                ElseIf line.ToUpper().Contains("MALE") OrElse line.ToUpper().Contains("LALAKI") Then
                    cboGender.Text = "MALE"
                End If
            End If

            Dim mobileMatch As Match = Regex.Match(line, "\b09\d{9}\b")
            If mobileMatch.Success Then
                txtMobileNumber.Text = mobileMatch.Value
            End If
        Next
    End Sub

    Private Function CleanNameString(input As String) As String
        Return Regex.Replace(input, "[^a-zA-ZñÑ\s]", "").Trim()
    End Function

    Private Function IsHeaderKeyword(str As String) As Boolean
        Dim upper As String = str.ToUpper()
        Return upper.Contains("REPUBLIKA") OrElse upper.Contains("PILIPINAS") OrElse
               upper.Contains("PAMBANSANG") OrElse upper.Contains("IDENTITY") OrElse
               upper.Contains("DATE") OrElse upper.Contains("BIRTH") OrElse upper.Contains("SEX")
    End Function

    Private Sub btnSubmit_Click(sender As Object, e As EventArgs) Handles btnSubmit.Click
        If lblLastnameError.ForeColor = Color.Red OrElse lblFirstnameError.ForeColor = Color.Red OrElse
           lblStreetAddressError.ForeColor = Color.Red OrElse lblBirthPlaceError.ForeColor = Color.Red OrElse
           lblMobileError.ForeColor = Color.Red OrElse lblEmailError.ForeColor = Color.Red OrElse
           lblUsernameError.ForeColor = Color.Red OrElse lblConfirmPassError.ForeColor = Color.Red OrElse
           profileImageBytes Is Nothing OrElse idFrontImageBytes Is Nothing OrElse idBackImageBytes Is Nothing Then

            MsgBox("Please resolve all validation errors and upload all required images (Profile, ID Front, ID Back) before submitting!", MsgBoxStyle.Exclamation, "Validation Error")
            Return
        End If

        Dim suffixVal As String = If(cboSuffix.Text = "N/A", "", " " & cboSuffix.Text.Trim().ToUpper())
        Dim middleVal As String = If(String.IsNullOrWhiteSpace(txtMiddlename.Text), "", " " & txtMiddlename.Text.Trim().ToUpper())
        Dim fullName As String = $"{txtLastname.Text.Trim().ToUpper()}, {txtFirstname.Text.Trim().ToUpper()}{middleVal}{suffixVal}"
        Dim fullAddress As String = $"{txtStreetAddress.Text.Trim().ToUpper()}, {txtBarangay.Text.Trim().ToUpper()}, {txtCity.Text.Trim().ToUpper()}"

        Dim freshResidentCode As String = GetNextResidentCode()
        Dim adminDeptID As Integer = 1

        Try
            connection()

            Dim eCount As Integer = 0
            sql = "SELECT COUNT(*) FROM residences WHERE LOWER(Email) = LOWER(@email)"
            Using cmdCheck2 As New MySqlCommand(sql, cn)
                cmdCheck2.Parameters.AddWithValue("@email", txtEmail.Text.Trim().ToLower())
                eCount = Convert.ToInt32(cmdCheck2.ExecuteScalar())
            End Using
            If eCount > 0 Then
                MsgBox("Email address is already registered!", MsgBoxStyle.Critical, "Duplicate Error")
                CloseConnection()
                Return
            End If

            Dim mCount As Integer = 0
            sql = "SELECT COUNT(*) FROM residences WHERE MobileNumber = @mobile"
            Using cmdCheck3 As New MySqlCommand(sql, cn)
                cmdCheck3.Parameters.AddWithValue("@mobile", txtMobileNumber.Text.Trim())
                mCount = Convert.ToInt32(cmdCheck3.ExecuteScalar())
            End Using
            If mCount > 0 Then
                MsgBox("Mobile number is already registered!", MsgBoxStyle.Critical, "Duplicate Error")
                CloseConnection()
                Return
            End If

            Try
                sql = "SELECT AdminID FROM admin WHERE FullName=@adminname"
                cmd = New MySqlCommand(sql, cn)
                cmd.Parameters.AddWithValue("@adminname", LoggedFullname)
                dr = cmd.ExecuteReader()
                If dr.Read() Then
                    adminDeptID = Convert.ToInt32(dr("AdminID"))
                End If
                dr.Close()
            Catch ex As Exception
                adminDeptID = 1
            End Try

            sql = "INSERT INTO residences (ResidentCode, Lastname, Firstname, Middlename, Suffix, FullName, Address, Birthday, BirthPlace, CivilStatus, Gender, MobileNumber, Email, Nationality, Picture, IdentificationFront, IdentificationBack, AccountStatus, DepartmentID) " &
                   "VALUES (@rcode, @lname, @fname, @mname, @suffix, @fullname, @address, @bday, @bplace, @cstatus, @gender, @mobile, @email, 'FILIPINO', @pic, @idfront, @idback, 'Active', @deptid)"

            cmd = New MySqlCommand(sql, cn)
            cmd.Parameters.AddWithValue("@rcode", freshResidentCode)
            cmd.Parameters.AddWithValue("@lname", txtLastname.Text.Trim().ToUpper())
            cmd.Parameters.AddWithValue("@fname", txtFirstname.Text.Trim().ToUpper())
            cmd.Parameters.AddWithValue("@mname", txtMiddlename.Text.Trim().ToUpper())
            cmd.Parameters.AddWithValue("@suffix", cboSuffix.Text.Trim().ToUpper())
            cmd.Parameters.AddWithValue("@fullname", fullName)
            cmd.Parameters.AddWithValue("@address", fullAddress)
            cmd.Parameters.AddWithValue("@bday", dtpBirthday.Value.ToString("yyyy-MM-dd"))
            cmd.Parameters.AddWithValue("@bplace", txtBirthPlace.Text.Trim().ToUpper())
            cmd.Parameters.AddWithValue("@cstatus", cboCivilStatus.Text.ToUpper())
            cmd.Parameters.AddWithValue("@gender", cboGender.Text.ToUpper())
            cmd.Parameters.AddWithValue("@mobile", txtMobileNumber.Text.Trim())
            cmd.Parameters.AddWithValue("@email", txtEmail.Text.Trim().ToLower())

            If profileImageBytes IsNot Nothing Then
                cmd.Parameters.Add("@pic", MySqlDbType.LongBlob).Value = profileImageBytes
            Else
                cmd.Parameters.Add("@pic", MySqlDbType.LongBlob).Value = DBNull.Value
            End If

            If idFrontImageBytes IsNot Nothing Then
                cmd.Parameters.Add("@idfront", MySqlDbType.LongBlob).Value = idFrontImageBytes
            Else
                cmd.Parameters.Add("@idfront", MySqlDbType.LongBlob).Value = DBNull.Value
            End If

            If idBackImageBytes IsNot Nothing Then
                cmd.Parameters.Add("@idback", MySqlDbType.LongBlob).Value = idBackImageBytes
            Else
                cmd.Parameters.Add("@idback", MySqlDbType.LongBlob).Value = DBNull.Value
            End If

            cmd.Parameters.AddWithValue("@deptid", adminDeptID)

            cmd.ExecuteNonQuery()
            MsgBox("Successfully Registered New Resident!", MsgBoxStyle.Information, "Success")

            ClearForm()
            GenerateResidentCode()

        Catch ex As MySqlException
            If ex.Number = 1062 Then
                MsgBox("Database constraint conflict (Error 1062): " & ex.Message, MsgBoxStyle.Critical, "MySQL Index Conflict")
            Else
                MsgBox("Database Error: " & ex.Message, MsgBoxStyle.Critical, "Error")
            End If
        Catch ex As Exception
            MsgBox("Error: " & ex.Message, MsgBoxStyle.Critical, "Error")
        Finally
            CloseConnection()
        End Try
    End Sub

    Private Sub ClearForm()
        txtLastname.Clear()
        txtFirstname.Clear()
        txtMiddlename.Clear()
        cboSuffix.SelectedIndex = 0
        txtStreetAddress.Clear()
        dtpBirthday.Value = DateTime.Now
        txtBirthPlace.Clear()
        cboCivilStatus.SelectedIndex = 0
        cboGender.SelectedIndex = 0
        txtMobileNumber.Clear()
        txtEmail.Clear()
        txtUsername.Clear()
        txtUsername.Tag = "AutoGenerated"
        txtPassword.Clear()
        txtConfirmPass.Clear()
        picUser.Image = Nothing
        picIDFront.Image = Nothing
        picIDBack.Image = Nothing
        profileImageBytes = Nothing
        idFrontImageBytes = Nothing
        idBackImageBytes = Nothing
        ClearAllValidationLabels()
    End Sub

    Private Sub btnExit_Click(sender As Object, e As EventArgs) Handles btnCancel.Click
        If MsgBox("Are you sure you want to Cancel?", vbYesNo + MsgBoxStyle.Question, "Confirm Cancel") = MsgBoxResult.Yes Then
            ClearForm()
            Me.Hide()
            frmMain.Enabled = True
            frmMain.TopMost = True
            Me.TopMost = False
        End If
    End Sub

End Class